### ISSUE TITLE
Jan, 1st 1900 was a Monday

### ISSUE THREAD

**Issue by akond** [gersak/vura#1]
But
```
(-> #inst "1900-01-01"
	  (v/date->value)
	  (v/day-context)
	  :day)
```
gives me 2, which is tuesday, I presume.

**Comment by gersak** [comment]
Hi, sry for late reply I've been quite busy closing this years projects.

#inst "1900-01-01" returns UTC value at that moment. That's fine, but if you are trying to get value for that date, than _v/date->value_ is calculating in your timezone. That means that at that point in time in your timezone it could be Tuesday. Try using *with-time-configuration* for more complex timezone computations.

Could you try following?

``` clojure
(-> #inst "1900-01-01" v/date->utc-value v/day-context :day)
```

The thing is that above approach is going to break things anyway. There just isn't enough context in the above statement. This is one of things that this project is trying to solve. 


#inst "1900-01-01" - where? What was time at _where_ place... So the following should work:

``` clojure
(->
   (v/date 1900 1 1)      ;; Creates Date for your timezone
   v/date->value          ;; Calculates value of that date with specified *offest* ( this means *your* timezone offset if not specified otherwise)
   v/day-context :day)  
```
 
I've been working a lot on timezones and state/religion holidays but haven't had time to finish next release.

Whole point of algebra computation beside +,-,*,/,round-number is that vura  _time_ converts it to UTC value(in respect to *time-configuration*) and afterwards you can return some computed value to i.e. different timezone or your local timezone. Or take date in some other timezone convert it to value and afterwards take that value and convert it to your timezone.

If some of the above doesn't work, please reply. There is a lot of new stuff prepared for next release

**Comment by akond** [comment]
```
(->
	(v/date 1900 1 1)
	v/date->value
	v/day-context :day)  
=> 7
```

**Comment by gersak** [comment]
If you are using version 0.5.2, could you please test the same with current version 0.5.3-SNAPSHOT?

It works on this version on my local environment. Can you reproduce it with version 0.5.3-SNAPSHOT? 

TY

**Comment by akond** [comment]
Now I get:

`(require '[vura.core :as v])`

> CompilerException java.io.FileNotFoundException: Could not locate vura/timezones/db__init.class or vura/timezones/db.clj on classpath., compiling:(vura/core.cljc:1:1)

**Comment by gersak** [comment]
Could you retry... I've uploaded new version. Once again it is work in progress, and alot has changed from version 0.5.2
